# 1.consider a one dimensional array Z build a two dimensional array whose first row is the (Z[0], Z[1],Z[2]) And each subsequent row is shifted by one last row should be (Z [-3], Z[-2],Z[-1])? and create 4 sub arrays with the created two-dimensional array.

In [1]:
import numpy as np

# Create a one-dimensional array
Z = np.arange(10)

# Reshape the one-dimensional array into a two-dimensional array
Z_2d = np.reshape(Z, (-1, 3))  # Reshape into (n, 3) where n is automatically determined

# Create the first row and the last row
first_row = Z[:3]
last_row = Z[-3:]

# Shift the rows
shifted_rows = np.roll(Z_2d, shift=1, axis=0)

# Replace the first row and the last row
shifted_rows[0] = first_row
shifted_rows[-1] = last_row

# Split the two-dimensional array into four subarrays
sub_arrays = np.split(shifted_rows, 4)

# Print the subarrays
for i, sub_array in enumerate(sub_arrays):
    print(f"Subarray {i + 1}:")
    print(sub_array)
    print()

ValueError: cannot reshape array of size 10 into shape (3)

In [7]:
import numpy as np

print("Creating 8X3 array using numpy.arange")
sampleArray = np.arange(10, 34, 1)
sampleArray = sampleArray.reshape(8,3)
print(sampleArray)

print("\nDividing 8X3 array into 4 sub array\n")
subArrays = np.split(sampleArray, 4)
print(subArrays)

Creating 8X3 array using numpy.arange
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]

Dividing 8X3 array into 4 sub array

[array([[10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18],
       [19, 20, 21]]), array([[22, 23, 24],
       [25, 26, 27]]), array([[28, 29, 30],
       [31, 32, 33]])]


# 2.From is the input NumPy array delete column two and insert following new column in its place. Original 2D array:[[34 43 73] [82 22 12] [53 94 66]]. New column: [[10, 10,10]]

In [2]:
import numpy as np

# Original 2D array
original_array = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])

# New column to insert
new_column = np.array([[10, 10, 10]])

# Delete column two
deleted_column_array = np.delete(original_array, 1, axis=1)

# Insert the new column in its place
modified_array = np.insert(deleted_column_array, 1, new_column, axis=1)

print("Modified Array:")
print(modified_array)

Modified Array:
[[34 10 73]
 [82 10 12]
 [53 10 66]]


# 3. Consider a set of 10 triplets (10X3 matrix) describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles

In [3]:
import numpy as np

# Suppose 'triangles' is a 10x3 matrix describing 10 triangles (with shared vertices)
# Each row represents a triangle, with three columns representing the vertices of each triangle
triangles = np.array([
    [1, 2, 3],
    [2, 3, 4],
    [3, 4, 5],
    [4, 5, 6],
    [5, 6, 7],
    [6, 7, 8],
    [7, 8, 9],
    [8, 9, 10],
    [9, 10, 11],
    [10, 11, 12]
])

# Function to extract line segments from a triangle
def extract_line_segments(triangle):
    line_segments = set()
    for i in range(len(triangle)):
        # Extract line segment between consecutive vertices
        segment = tuple(sorted([triangle[i], triangle[(i+1)%3]]))
        line_segments.add(segment)
    return line_segments

# Set to store unique line segments
unique_line_segments = set()

# Iterate over each triangle and extract line segments
for triangle in triangles:
    line_segments = extract_line_segments(triangle)
    unique_line_segments.update(line_segments)

print("Set of unique line segments composing all the triangles:")
print(unique_line_segments)

Set of unique line segments composing all the triangles:
{(1, 3), (10, 11), (4, 5), (5, 6), (8, 9), (9, 10), (2, 3), (11, 12), (7, 9), (1, 2), (3, 5), (6, 7), (4, 6), (6, 8), (5, 7), (8, 10), (10, 12), (9, 11), (3, 4), (7, 8), (2, 4)}
