# There are number of mathematical operations which could be performed with Numpy arrays:-
1. Trigonometric functions
2. Logarithmic functions
3. Inverse functions
4. Exponential functions
5. Statistical functions

In [1]:
import numpy as np

In [2]:
arr = np.array([1,3,5,2,6])

#cosine value of each element of the array
np.cos(arr)

array([ 0.54030231, -0.9899925 ,  0.28366219, -0.41614684,  0.96017029])

In [3]:
np.log(arr)

array([0.        , 1.09861229, 1.60943791, 0.69314718, 1.79175947])

In [4]:
np.mean(arr)

3.4

In [5]:
np.median(arr)

3.0

In [6]:
np.std(arr)

1.8547236990991407

In [7]:
np.exp(arr)

array([  2.71828183,  20.08553692, 148.4131591 ,   7.3890561 ,
       403.42879349])

In [10]:
arr1 = np.array([2,4,6,8,2])
arr2 = np.array([3,6,1,5,2])

In [11]:
arr1+arr2

array([ 5, 10,  7, 13,  4])

In [12]:
arr1-arr2

array([-1, -2,  5,  3,  0])

In [13]:
arr1*arr2

array([ 6, 24,  6, 40,  4])